// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectionList():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function TestConnection(arg1:string):Promise<string>;
