// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConnection(arg1) {
  return window['go']['main']['App']['AddConnection'](arg1);
}

export function ConnectToDBServer(arg1) {
  return window['go']['main']['App']['ConnectToDBServer'](arg1);
}

export function ConnectionList() {
  return window['go']['main']['App']['ConnectionList']();
}

export function GetCollectionItems(arg1, arg2) {
  return window['go']['main']['App']['GetCollectionItems'](arg1, arg2);
}

export function GetDBDetails(arg1) {
  return window['go']['main']['App']['GetDBDetails'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}
