// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddConnection(arg1) {
  return window['go']['main']['App']['AddConnection'](arg1);
}

export function ConnectToDB(arg1) {
  return window['go']['main']['App']['ConnectToDB'](arg1);
}

export function ConnectionList() {
  return window['go']['main']['App']['ConnectionList']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListDBS() {
  return window['go']['main']['App']['ListDBS']();
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}
